# Generated by Django 3.1.1 on 2020-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200923_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/book/'),
        ),
    ]
